diff_robot:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50

  # Position Controllers --------------------------------------
  motor_left_position_controller:
    type: effort_controllers/JointPositionController
    joint: to_left_motor
    pid: {p: 100.0, i: 0.01, d: 10.0}
  motor_right_position_controller:
    type: effort_controllers/JointPositionController
    joint: to_right_motor
    pid: {p: 100.0, i: 0.01, d: 10.0}
